<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Phantom.Workspaces.Containers</RootNamespace>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Phantom.Workspaces.Data.Core\Phantom.Workspaces.Data.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Phantom.Workspaces.Containers.Tests" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="JsonSchemas\*.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="JsonSchemas\*.json" />
  </ItemGroup>
</Project>