param(
    [string]$Package = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $repoRoot "docs\nuget\research"
$nugetRoot = Join-Path $env:USERPROFILE ".nuget\packages"

$targetPackages = @(
    "AgentSchema",
    "Avalonia",
    "Avalonia.Desktop",
    "Avalonia.Fonts.Inter",
    "Avalonia.Themes.Fluent",
    "AvaloniaUI.DiagnosticsSupport",
    "JsonSchema.Net",
    "Microsoft.Agents.AI",
    "Microsoft.Extensions.AI",
    "Microsoft.Extensions.AI.Abstractions",
    "ModelContextProtocol",
    "ModelContextProtocol.Core",
    "OllamaSharp",
    "System.CommandLine",
    "YamlDotNet"
)

if ($Package) {
    $targetPackages = @($targetPackages | Where-Object { $_ -eq $Package })
}

if ($targetPackages.Count -eq 0) {
    throw "No matching package target found."
}

function Normalize-Symbol([string]$symbol) {
    if ([string]::IsNullOrWhiteSpace($symbol)) { return $null }
    if ($symbol.Length -lt 3 -or $symbol[1] -ne ':') { return $null }

    $kind = $symbol[0]
    if ($kind -notin @('T', 'M', 'P', 'E', 'F')) { return $null }

    $value = $symbol.Substring(2)
    $value = $value -replace '\(.*\)$', ''
    $value = $value -replace '``\d+', ''
    $value = $value -replace '`\d+', ''
    $value = $value -replace '\+', '.'

    if ($value.EndsWith(".#ctor", [StringComparison]::Ordinal) -or $value.EndsWith(".#cctor", [StringComparison]::Ordinal)) {
        return $null
    }

    return $value
}

function Get-TfmRank([string]$tfm) {
    switch ($tfm) {
        "net10.0" { 100 }
        "net9.0" { 90 }
        "net8.0" { 80 }
        "net7.0" { 70 }
        "net6.0" { 60 }
        "net5.0" { 50 }
        "netstandard2.1" { 40 }
        "netstandard2.0" { 30 }
        default { 10 }
    }
}

function Resolve-LatestVersion([string]$packageId) {
    $packagePath = Join-Path $nugetRoot ($packageId.ToLowerInvariant())
    if (!(Test-Path $packagePath)) { return $null }

    $versions = Get-ChildItem $packagePath -Directory | Sort-Object Name -Descending
    if (!$versions) { return $null }
    return $versions[0].Name
}

function Resolve-XmlFiles([string]$packageId, [string]$version) {
    $libPath = Join-Path (Join-Path (Join-Path $nugetRoot ($packageId.ToLowerInvariant())) $version) "lib"
    if (!(Test-Path $libPath)) { return @() }

    $bestTfm = Get-ChildItem $libPath -Directory |
        Sort-Object @{ Expression = { Get-TfmRank $_.Name }; Descending = $true }, @{ Expression = { $_.Name }; Descending = $true } |
        Select-Object -First 1

    if ($null -eq $bestTfm) { return @() }
    return @(Get-ChildItem $bestTfm.FullName -Filter "*.xml" -File)
}

New-Item -ItemType Directory -Force $outDir | Out-Null

foreach ($packageId in $targetPackages) {
    $version = Resolve-LatestVersion $packageId
    if ($null -eq $version) {
        Write-Warning "Package '$packageId' not found in $nugetRoot. Skipping."
        continue
    }

    $xmlFiles = @(Resolve-XmlFiles $packageId $version)

    $symbols = [System.Collections.Generic.SortedSet[string]]::new()
    if ($xmlFiles.Count -eq 0) {
        Write-Warning "No XML docs found for '$packageId' ($version). Writing placeholder file."
    }
    else {
        foreach ($xmlFile in $xmlFiles) {
            [xml]$doc = Get-Content $xmlFile.FullName -Raw
            if ($null -eq $doc.doc -or $null -eq $doc.doc.members -or !($doc.doc.members.PSObject.Properties.Name -contains "member")) {
                continue
            }

            foreach ($member in @($doc.doc.members.member)) {
                $normalized = Normalize-Symbol $member.name
                if ($null -ne $normalized) {
                    $null = $symbols.Add($normalized)
                }
            }
        }
    }

    $apiLines = @($symbols)
    $sourceList = if ($xmlFiles.Count -eq 0) {
        "- none (package does not ship XML docs in the selected TFM)"
    }
    else {
        ($xmlFiles | ForEach-Object { "- ``$($_.Name)``" }) -join "`r`n"
    }
    $mdPath = Join-Path $outDir "$packageId.md"

    $apiBody = $apiLines -join "`r`n"
    $markdown = @"
# $packageId — Public API Reference

Generated by scripts\research-nuget-apis.ps1.
Package version: $version
Entries: $($apiLines.Count)

Each API entry is a fully-qualified dotted symbol for trivial search.

## Source XML files
$sourceList

## Regenerate

~~~powershell
# From repo root:
.\scripts\research-nuget-apis.ps1 -Package "$packageId"
~~~

## API

~~~
$apiBody
~~~
"@

    Set-Content -Path $mdPath -Value $markdown -Encoding UTF8
}
