<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Phantom.Workspaces.Docs</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Link="README.md" />
    <None Include="..\docs\**\*.md" Link="docs\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
