<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Phantom.Workspaces\Phantom.Workspaces.csproj" />
    <ProjectReference Include="..\Phantom.Workspaces.Data.Web.Client\Phantom.Workspaces.Data.Web.Client.csproj" />
  </ItemGroup>
</Project>
